# Generated by Django 4.1.2 on 2022-10-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffmpeg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
